const data = [
  {
    pid: "1",
    name: "pingme",
    tagline: "Social Network Website",
    color: "#c2c880",
    textcolor: "black",
    time: "25 days",
    cover_image: "../mockups/mu_pingme.jpg",
    web_images: [
      "../projects/p1.png",
      "../projects/p2.png",
      "../projects/p3.png",
    ],
    mob_images: [
      "../projects/mob_p4.png",
      "../projects/mob_p3.png",
      "../projects/mob_p1.png",
      "../projects/mob_p2.png",
    ],
    tech_images: [
      "../skills/react.png",
      "../skills/redux.png",
      "../skills/mongodb.png",
      "../skills/css.png",
      "../skills/express.png",
      "../skills/js.png",
      "../skills/nodejs.png",
    ],
    content:
      "Utilised MongoDB, Express js, React js, Node js and Socket io. Website offers functionalities like user Authentication, update profile pictures, post pictures, chat with others users, follow unfollow other users etc.",
    github: "https://github.com/punitbhesota/pingme.git",
    live: "",
  },
  {
    pid: "2",
    name: "the coinstock",
    tagline: "Crypto price tracking website",
    textcolor: "white",
    time: "5 days",
    color: "#19381f",
    cover_image: "../mockups/mu_cs_e.png",
    web_images: [
      "../projects/csw1.png",
      "../projects/csw2.png",
      "../projects/csw3.png",
    ],
    mob_images: [
      "../projects/csm1.png",
      "../projects/csm2.png",
      "../projects/csm3.png",
    ],

    tech_images: [
      "../skills/react.png",
      "../skills/css.png",
      "../skills/sass.png",
      "../skills/js.png",
      "../skills/nodejs.png",
      "../skills/firebase.png",
    ],
    content:
      "Developed and designed with React js. Website tracks different cryptocurrencies' prices and historic data. Functionality to create a watchlist and keep track of favourite cryptocurrencies.",
    github: "https://github.com/punitbhesota/coinstock.git",
    live: "https://thecoinstock.web.app",
  },
  {
    pid: "3",
    name: "homecookd",
    tagline: "Food ordering website",
    color: "orange",
    textcolor: "white",
    time: "15 days",
    cover_image: "../mockups/mu_client_e.png",
    web_images: [
      "../projects/hcw1.png",
      "../projects/hcw3.png",
      "../projects/hcaw1.png",
      "../projects/hcaw2.png",
      "../projects/hcaw3.png",
      "../projects/hcaw4.png",
    ],
    mob_images: ["../projects/hcm1.png", "../projects/hcam1.png"],

    tech_images: [
      "../skills/react.png",
      "../skills/css.png",
      "../skills/js.png",
      "../skills/nodejs.png",
      "../skills/figma.png",
      "../skills/aws.png",
    ],
    content:
      "Homecookd.org is a client project it consists of a basis product website and an admin dashboard.Utilized reactjs for this project.",
    github: "",
    live: "https://homecookd.org",
  },
  {
    pid: "4",
    name: "Shhopily",
    tagline: "E commerce website",
    time: "30 days",
    textcolor: "white",
    color: "grey",
    cover_image: "../mockups/mu_ecom.jpg",
    web_images: [
      "../projects/ecomw1.png",
      "../projects/ecomw2.png",
      "../projects/ecomw3.png",
      "../projects/ecomw4.png",
      "../projects/ecomw6.png",
    ],
    mob_images: [
      "../projects/ecom1.png",
      "../projects/ecom2.png",
      "../projects/ecom3.png",
      "../projects/ecom4.png",
    ],

    tech_images: [
      "../skills/react.png",
      "../skills/redux.png",
      "../skills/js.png",
      "../skills/bootstrap.png",
      "../skills/aws.png",
      "../skills/heroku.png",
    ],
    content:
      "Developed with MongoDB, Express , React , Node js, Redux etc. Functionalities include Admin dashboard, User Authentication, product reviews and ratings, embedded payment methods (Paypal, Debit card, Credit cards) etc.",
    live: "https://shhopily.herokuapp.com",
    github: "https://github.com/punitbhesota/shhopily.git",
  },
  {
    pid: "5",
    name: "mygym",
    tagline: "Gym management app",
    color: "orange",
    textcolor: "white",
    time: "1 week",
    cover_image: "../mockups/mu_gym2.jpg",
    mob_images: [
      "../projects/mg1.jpg",
      "../projects/mg2.jpg",
      "../projects/mg3.jpg",
      "../projects/mg4.jpg",
      "../projects/mg5.jpg",
    ],
    tech_images: [
      "../skills/native.png",
      "../skills/js.png",
      "../skills/nodejs.png",
      "../skills/mongodb.png",
      "../skills/express.png",
    ],
    content:
      "Developed using react native. It offers functionalities to create an admin account and manage daily tasks of a gym",
    live: "",
    github: "",
  },

  {
    pid: "6",
    name: "the coinstock app",
    tagline: "A cryptocurrency price tracking app",
    color: "orange",
    time: "1 week",
    textcolor: "white",
    cover_image: "../mockups/mu_csa_ee.jpg",
    mob_images: [
      "../projects/csapp1.jpg",
      "../projects/csapp2.jpg",
      "../projects/csapp3.jpg",
      "../projects/csm3.png",
    ],
    tech_images: [
      "../skills/native.png",
      "../skills/js.png",
      "../skills/nodejs.png",
      "../skills/mongodb.png",
      "../skills/express.png",
    ],
    content:
      "Developed and designed with React Native. Website tracks different cryptocurrencies' prices and historic data. Includes functionalities to create an account and a watchlist to keep track of favourite cryptocurrencies.",
    live: "",
    github: "",
  },
];
export { data };
